// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBzNdQhOb8PVPioKImCOcZ9CEoK2sVUg',
    appId: '1:93446101103:web:f7be5c67179ae9bfe7159a',
    messagingSenderId: '93446101103',
    projectId: 'we-chats-46946',
    authDomain: 'we-chats-46946.firebaseapp.com',
    storageBucket: 'we-chats-46946.appspot.com',
    measurementId: 'G-LQDM40KZ8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUcK2w1o2-tJ5xaRhe3gmUMuDrzbzyweg',
    appId: '1:93446101103:android:48ad172309e43ae9e7159a',
    messagingSenderId: '93446101103',
    projectId: 'we-chats-46946',
    storageBucket: 'we-chats-46946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBecOHcf8SrU7_GeXcvs6Ootsh7NewZSc0',
    appId: '1:93446101103:ios:1770218d9d5c9f67e7159a',
    messagingSenderId: '93446101103',
    projectId: 'we-chats-46946',
    storageBucket: 'we-chats-46946.appspot.com',
    androidClientId: '93446101103-itc5a19bfbu734qvb79ba6qgqbr9mhvf.apps.googleusercontent.com',
    iosClientId: '93446101103-q8pc64kjngq1961f7ah2963ij1pp92q3.apps.googleusercontent.com',
    iosBundleId: 'com.nurehub.handygo',
  );

}